# Generated by Django 5.2.4 on 2025-12-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_homepage', '0004_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
